// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCubDYXP6-xM3qOM9laVO1DCWJsfagc_MU',
    appId: '1:440615955255:web:9f72d5bbabfcc5decc08b2',
    messagingSenderId: '440615955255',
    projectId: 'api1-6e4a3',
    authDomain: 'api1-6e4a3.firebaseapp.com',
    databaseURL: 'https://api1-6e4a3-default-rtdb.firebaseio.com',
    storageBucket: 'api1-6e4a3.firebasestorage.app',
    measurementId: 'G-PQPC9ZTWFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCezDWW42hmMH1gyls4iS1fSa8Me0EqA00',
    appId: '1:440615955255:android:3b33d0b102e05efecc08b2',
    messagingSenderId: '440615955255',
    projectId: 'api1-6e4a3',
    databaseURL: 'https://api1-6e4a3-default-rtdb.firebaseio.com',
    storageBucket: 'api1-6e4a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkW5kjyfdpnemCH6gAayahi3l9CGYXZIg',
    appId: '1:440615955255:ios:5fadd666b9252337cc08b2',
    messagingSenderId: '440615955255',
    projectId: 'api1-6e4a3',
    databaseURL: 'https://api1-6e4a3-default-rtdb.firebaseio.com',
    storageBucket: 'api1-6e4a3.firebasestorage.app',
    androidClientId: '440615955255-23p0qrc0acrukf8th7so0i0jl79kfiep.apps.googleusercontent.com',
    iosClientId: '440615955255-v70t1clbks9kidjpcmoqhr7c28s6ijcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.apii',
  );
}
